// =========================================================
// ADHD VPU Firmware Dispatcher (Auto-Generated by Python)
// =========================================================
#include <stdint.h>

static inline void dispatch_sub_ops() {

    // --- Dispatching Macro: Attention ---
    __asm__ volatile("csrw 0x801, %0" :: "r"(0x00000000E0000000ULL));
    __asm__ volatile("csrw 0x802, %0" :: "r"(0x00000000E0008000ULL));
    __asm__ volatile("csrw 0x803, %0" :: "r"(0x00000000E0018000ULL));
    __asm__ volatile("csrw 0x804, %0" :: "r"(0x00000000E0010000ULL));
    __asm__ volatile("csrw 0x805, %0" :: "r"(0x0300030003000300ULL));
    __asm__ volatile("csrw 0x806, %0" :: "r"(0x0000000220440841ULL));
    __asm__ volatile("csrw 0x807, %0" :: "r"(0x00000000F8C44080ULL));
    __asm__ volatile("csrw 0x808, %0" :: "r"(0x0000000020411042ULL));
    __asm__ volatile("csrw 0x809, %0" :: "r"(0x0000002000400040ULL));
    __asm__ volatile("csrw 0x80A, %0" :: "r"(0x0000400200020003ULL));

    // --- Dispatching Macro: Projection ---
    __asm__ volatile("csrw 0x801, %0" :: "r"(0x00000000E0078000ULL));
    __asm__ volatile("csrw 0x802, %0" :: "r"(0x00000000E00D8000ULL));
    __asm__ volatile("csrw 0x803, %0" :: "r"(0x00000000E0168000ULL));
    __asm__ volatile("csrw 0x804, %0" :: "r"(0x00000000E0010000ULL));
    __asm__ volatile("csrw 0x805, %0" :: "r"(0x0300030003000300ULL));
    __asm__ volatile("csrw 0x806, %0" :: "r"(0x0000000220440841ULL));
    __asm__ volatile("csrw 0x807, %0" :: "r"(0x00000000F8C42080ULL));
    __asm__ volatile("csrw 0x808, %0" :: "r"(0x0000000020411042ULL));
    __asm__ volatile("csrw 0x809, %0" :: "r"(0x0000002000400040ULL));
    __asm__ volatile("csrw 0x80A, %0" :: "r"(0x0003000300020001ULL));

    // --- Dispatching Macro: Fnn_GELU ---
    __asm__ volatile("csrw 0x801, %0" :: "r"(0x00000000E01C8000ULL));
    __asm__ volatile("csrw 0x802, %0" :: "r"(0x00000000E0228000ULL));
    __asm__ volatile("csrw 0x803, %0" :: "r"(0x00000000E0468000ULL));
    __asm__ volatile("csrw 0x804, %0" :: "r"(0x00000000E0010000ULL));
    __asm__ volatile("csrw 0x805, %0" :: "r"(0x03000C000C000300ULL));
    __asm__ volatile("csrw 0x806, %0" :: "r"(0x0000000220440841ULL));
    __asm__ volatile("csrw 0x807, %0" :: "r"(0x0000000178C42080ULL));
    __asm__ volatile("csrw 0x808, %0" :: "r"(0x0000000020411042ULL));
    __asm__ volatile("csrw 0x809, %0" :: "r"(0x0000002000400040ULL));
    __asm__ volatile("csrw 0x80A, %0" :: "r"(0x0003000C00020002ULL));
}
